added "exit 1" to trap; moved trap in front of lock directory creation; the trap is now removed before deleting the lock directory
git-svn-id: svn://svn.code.sf.net/p/docutils/code/trunk@3258 929543f6-e4f2-0310-98a6-ba3bd3dd1d04

diff --git a/sandbox/davidg/infrastructure/docutils-update b/sandbox/davidg/infrastructure/docutils-update
--- a/sandbox/davidg/infrastructure/docutils-update
+++ b/sandbox/davidg/infrastructure/docutils-update
@@ -85,7 +85,8 @@ if ! mkdir $lockdir; then
     echo and delete the directory.
     exit 1
 fi
-trap "rm -rf $lockdir" 0 1 2 3 15
+# Always clean up on exit.
+trap "rm -rf $lockdir; exit 1" 0 1 2 3 15
 # Make sure the lock directory is deletable (i.e. rwx) by other group
 # members (in case this script crashes after copying files into the
 # directory) and un-readable by world (because we'll be storing the
@@ -217,6 +218,7 @@ mv $htdocs_new_tarball $htdocs_tarball
 
 # Tidy up.
 rm -f $htdocs_patchfile
+trap - 0 1 2 3 15
 rm -rf $lockdir
 test $feedback && echo '...docutils-update done.' || true
 
